Resolved review comments

diff --git a/target/bin/fetchmailrc_split b/target/bin/fetchmailrc_split
--- a/target/bin/fetchmailrc_split
+++ b/target/bin/fetchmailrc_split
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /bin/bash
 # Description: This script will split the content of /etc/fetchmailrc into
 #              smaller fetchmailrc files per server [poll] entries. Each
 #              separate fetchmailrc file is stored in /etc/fetchmailrc.d
@@ -13,43 +13,43 @@ FETCHMAILRCD="/etc/fetchmailrc.d"
 DEFAULT_FILE="${FETCHMAILRCD}/defaults"
 
 # Pre checks, check if needed files and folders exists
-if [ ! -r "${FETCHMAILRC}" ]
+if [[ ! -r "${FETCHMAILRC}" ]]
 then
-	echo "Error: File ${FETCHMAILRC} not found"
-	exit 1
+  echo "Error: File ${FETCHMAILRC} not found"
+  exit 1
 fi
 
-if [ ! -d "${FETCHMAILRCD}" ]
+if [[ ! -d "${FETCHMAILRCD}" ]]
 then
-	if ! mkdir "${FETCHMAILRCD}";
-	then
-		echo "Error: Unable to create folder ${FETCHMAILRCD}"
-		exit 1
-	fi
+  if ! mkdir "${FETCHMAILRCD}";
+  then
+    echo "Error: Unable to create folder ${FETCHMAILRCD}"
+    exit 1
+  fi
 fi
 
 COUNTER=0
 SERVER=0
-while read -r line
+while read -r LINE
 do
-	if [[ "${line}" =~ poll ]]
-	then
-		# If we read "poll" then we reached a new server definition
-		# We need to create a new file with fetchmail defaults from
-		# /etc/fetcmailrc
-		COUNTER=$((COUNTER+1))
-		SERVER=1
-		cat "${DEFAULT_FILE}" > "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
-		echo "${line}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
-	elif [ "${SERVER}" -eq 0 ]
-	then
-		# We have not yet found "poll". Let's assume we are still reading
-		# the default settings from /etc/fetchmailrc file
-		echo "${line}" >> "${DEFAULT_FILE}"
-	else
-		# Just the server settings that need to be added to the specific rc.d file
-		echo "${line}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
-	fi
+  if [[ "${LINE}" =~ poll ]]
+  then
+    # If we read "poll" then we reached a new server definition
+    # We need to create a new file with fetchmail defaults from
+    # /etc/fetcmailrc
+    COUNTER=$((COUNTER+1))
+    SERVER=1
+    cat "${DEFAULT_FILE}" > "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+    echo "${LINE}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+  elif [[ "${SERVER}" -eq 0 ]]
+  then
+    # We have not yet found "poll". Let's assume we are still reading
+    # the default settings from /etc/fetchmailrc file
+    echo "${LINE}" >> "${DEFAULT_FILE}"
+  else
+    # Just the server settings that need to be added to the specific rc.d file
+    echo "${LINE}" >> "${FETCHMAILRCD}/fetchmail-${COUNTER}.rc"
+  fi
 done < "${FETCHMAILRC}"
 
 # Cleaning
